CREATE TABLE users (
  id SERIAL,
  email VARCHAR(255) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  type SMALLINT NOT NULL DEFAULT 1,
  status SMALLINT NOT NULL DEFAULT 0,
  password TEXT NOT NULL,
  PRIMARY KEY (id)
);